name: Run Python Script

on:
  schedule:
    - cron: '*/1 * * * *'  # 每 1 分钟触发一次
  push:
    branches:
      - main  # 或者您預設的分支名稱
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # 選擇您需要的 Python 版本
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run script with API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}  # 设置环境变量
      run: |
        python get_repo_unique_clone_counts.py $API_KEY
        python get_repo_unique_views.py $API_KEY

    - name: List files
      run: ls -la
  
    - name: Upload generated image
      uses: actions/upload-artifact@v3
      with:
          name: generated-image
          path: |
            github_clone_counts.png
            github_visitor.png

    - name: Commit and push to another repository
      env:
        ACCESS_TOKEN: ${{ secrets.API_KEY }}
      run: |
        git config --global user.email "weitsunglin@igs.com"
        git config --global user.name "weitsunglin"
        git clone https://github.com/weitsunglin/weitsunglin.git
        cp github_clone_counts.png weitsunglin/github_clone_counts.png
        cp github_visitor.png weitsunglin/github_visitor.png
        cd weitsunglin
        git add github_clone_counts.png
        git add github_visitor.png
        if [[ $(git status --porcelain) ]]; then
          git commit -m "Update from GitHub Actions"
          git push https://weitsunglin:${ACCESS_TOKEN}@github.com/weitsunglin/weitsunglin.git main
        else
          echo "No changes to commit."
        fi
